
# Setup
title:            dancmj
tagline:          'My personal blog'
description:      A dev blog about my projects, ideas and whereabouts.
baseurl:          /

author:
  name:             'Daniel Contreras'
  url:              http://dancmj.net
  twitter_username: dan_cmj
  github_username:  dancmj
  email:            daniel.c82@gmail.com

paginate:         5

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dancmj/dancmj.github.io
