name             : dancmj
description      : hi, my name is dan and this is my blog!
meta_description : A place for my thoughts, games and projects.

github_username  : dancmj
twitter_username : dan_cmj
email            : hello@dancmj.net

markdown         : kramdown
highlighter      : pygments
logo             : false
paginate         : 5
baseurl          : /
domain_name      : http://dancmj.github.io
google_analytics : UA-58503726-1

url              : http://dancmj.github.io
author           : Daniel Contreras

gems             : [jekyll-paginate, jekyll-gist]
