name:               dancmj
description:        Blogging about stuffs
meta_description:   "A place for my thoughts, games and projects"

markdown:           redcarpet
highlighter:        pygments
logo:               false
paginate:           15
baseurl:            /
domain_name:        'http://dancmj.github.io'
google_analytics:   'UA-58503726-1'

# Details for the RSS feed generator
url:                'http://dancmj.github.io'
author:             'Daniel Contreras'
