# site settings
title               : dan
subtitle          : cmj
email             : hello@dancmj.net
description       : Have a read on my thoughts and learnings. <br> The website is still being built, so <a href="/pf">check out my portfolio</a>.
baseurl           : /             # the subpath of your site, e.g. /blog
url               : http://dancmj.github.io # the base hostname & protocol for your site
author            : Daniel Contreras Mejia
street_address    :
city              : Vancouver
state             : BC
zip_code          :
country           : Canada
phone             : +1 (604) 723 0256

# homepage tiles
tiles-source      : posts # accepts "posts" or "pages"
tiles-count       : 6

# social settings
500px_url         :
facebook_url      :
github_url        : https://github.com/dancmj
gitlab_url        :
googleplus_url    :
instagram_url     : https://instagram.com/dancmj
linkedin_url      : https://www.linkedin.com/in/dancmj
pinterest_url     :
slack_url         :
twitter_url       : https://twitter.com/andrewbanchich
google_analytics  : UA-58503726-1
# build settings
markdown          : kramdown

sass:
  style           : compressed
